//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by netsdk_demo.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_JSNETDEMO_DIALOG            102
#define IDD__DEMO_DIALOG                102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_UPDATE               130
#define IDD_DIALOG_AC                   131
#define IDD_DIALOG_EMAIL                132
#define IDD_DIALOG_BPS                  133
#define IDD_DIALOG_COLOR                134
#define IDD_DIALOG_COM                  135
#define IDD_DIALOG_FTP                  136
#define IDD_DIALOG_MD                   137
#define IDD_DIALOG_NET                  138
#define IDD_DIALOG_OSD                  139
#define IDD_DIALOG_SENSOR_OUT           140
#define IDD_DIALOG_USER                 141
#define IDD_DIALOG_VIDEOLOSS            142
#define IDD_DIALOG_SENSOR_IN            143
#define IDD_DIALOG_ALARM                144
#define IDD_DIALOG_CA_MD                145
#define IDD_DIALOG_PORT                 146
#define IDD_DIALOG_CA_VL                147
#define IDD_DIALOG_CA_RECORD            148
#define IDD_DIALOG_DEV_RECORD           149
#define IDD_DIALOG_DEV_RECORD_SEARCH    150
#define IDD_DIALOG_USER_ADD             151
#define IDD_DIALOG_PRESET               152
#define IDD_DIALOG_HS                   153
#define IDD_DIALOG_SYSTEM               154
#define IDD_DIALOG_TIME                 155
#define IDD_DIALOG_AUDIO                156
#define IDD_DIALOG_3D_RECT              157
#define IDD_DIALOG_VIDEO_MASK           158
#define IDD_DIALOG_BALL_VIDEO_MASK      159
#define IDD_DIALOG_SEARCH_DEV           160
#define IDD_DIALOG_VIDEO                161
#define IDD_DIALOG_PTZ20                162
#define IDD_DIALOG_PTZ20_PRESET         163
#define IDR_CHS                         165
#define IDR_ENG                         166
#define IDD_DIALOG_WA                   167
#define IDD_DIALOG_ENCRYPT_STR          168
#define IDC_STATIC_VIDEO                1000
#define IDC_EDIT_ADDR                   1001
#define IDC_EDIT_IP                     1001
#define IDC_EDIT_CHANNEL                1002
#define IDC_EDIT_MAC                    1002
#define IDC_EDIT_TO_ADDR                1002
#define IDC_EDIT_PORT                   1003
#define IDC_COMBO_TYPE                  1004
#define IDC_EDIT_SUBMASK                1004
#define IDC_EDIT_USER                   1005
#define IDC_EDIT_PASSWORD               1006
#define IDC_BTN_PREVIEW_START           1007
#define IDC_BTN_PREVIEW_STOP            1008
#define IDC_EDIT_GATEWAY                1008
#define IDC_BTN_RECORD_START            1009
#define IDC_BTN_RECORD_STOP             1010
#define IDC_BTN_SNAP                    1011
#define IDC_CHECK_AUDIO_OUT             1012
#define IDC_EDIT_DNS                    1012
#define IDC_BTN_PTZ_UP                  1013
#define IDC_BTN_PTZ_DOWN                1014
#define IDC_BTN_PTZ_LEFT                1015
#define IDC_BTN_PTZ_RIGHT               1016
#define IDC_BTN_PTZ_ZOOM_ADD            1017
#define IDC_BTN_PTZ_ZOOM_SUB            1018
#define IDC_BTN_STOP                    1018
#define IDC_BTN_PTZ_FOCUS_ADD           1019
#define IDC_BTN_PTZ_FOCUS_SUB           1020
#define IDC_BTN_PTZ_IRISA_ADD           1021
#define IDC_BTN_PTZ_IRISA_SUB           1022
#define IDC_BTN_PTZ_AUTO                1023
#define IDC_BTN_SEARCH                  1024
#define IDC_EDIT_CHANNELS               1024
#define IDC_CHECK_ABC                   1025
#define IDC_BTN_PTZ_PRESET              1026
#define IDC_BTN_PTZ_TRACK               1027
#define IDC_CHECK_GUARDER               1027
#define IDC_CHECK_SENSOR_1              1028
#define IDC_EDIT_GUARDER_PERP           1028
#define IDC_CHECK_SENSOR_2              1029
#define IDC_EDIT_GUARDER_TIME           1029
#define IDC_BTN_GUARDER_SAVE            1030
#define IDC_BTN_PTZ_LIGHT_OPEN          1030
#define IDC_BTN_DEV_BPS                 1031
#define IDC_BTN_DEV_COLOR               1032
#define IDC_BTN_DEV_COM                 1033
#define IDC_BTN_DEV_MD                  1034
#define IDC_COMBO_TIMEZONE              1034
#define IDC_BTN_NET                     1035
#define IDC_BTN_OSD                     1036
#define IDC_EDIT_FILE                   1036
#define IDC_STATIC_WEEK                 1037
#define IDC_BTN_SYS                     1037
#define IDC_DATETIMEPICKER              1037
#define IDC_BTN_OPEN                    1037
#define IDC_BTN_PORT                    1038
#define IDC_BTN_TIME                    1039
#define IDC_BTN_TIMEZONE_GET            1040
#define IDC_BTN_USER                    1040
#define IDC_CHECK_ALARM                 1040
#define IDC_BTN_VL                      1041
#define IDC_CHECK_ALARM1                1041
#define IDC_BTN_UPDATE                  1042
#define IDC_CHECK_ALARM2                1042
#define IDC_BTN_TIMEZONE_SET            1043
#define IDC_CHECK_ALARM3                1043
#define IDC_BTN_SENSOR                  1043
#define IDC_BTN_AUDIO                   1044
#define IDC_CHECK_DHCP                  1045
#define IDC_BTN_DEV_REC                 1045
#define IDC_CHECK_WIFI_DHCP             1046
#define IDC_BTN_TIME_SET                1046
#define IDC_BTN_PTZ_LIGHT_CLOSE         1046
#define IDC_CHECK_WIFI_ENABLE           1047
#define IDC_BTN_PTZ_BRUSH_OPEN          1047
#define IDC_CHECK_WIFI_SECEN            1048
#define IDC_BTN_PTZ_BRUSH_CLOSE         1048
#define IDC_SLIDER_BRI                  1049
#define IDC_CHECK_WIFI_EXIST            1049
#define IDC_BTN_CA                      1049
#define IDC_BTN_CA_SENSOR_IN            1049
#define IDC_BTN_AC                      1050
#define IDC_BTN_EMAIL                   1051
#define IDC_SLIDER_SAT                  1052
#define IDC_BTN_FTP                     1052
#define IDC_EDIT_VERSION                1053
#define IDC_BTN_SENSOR_OUT              1053
#define IDC_EDIT_DEVICE_NAME            1054
#define IDC_BTN_CA_MD                   1054
#define IDC_EDIT_DEVICE_ID              1055
#define IDC_CHECK_SENSOR_OUT_1          1055
#define IDC_BTN_CA_VL                   1055
#define IDC_CHECK_SENSOR_OUT_2          1056
#define IDC_BTN_RECORD                  1056
#define IDC_SLIDER_CON                  1057
#define IDC_EDIT_VERSION_LINUX          1057
#define IDC_EDIT_HOLDTIME               1057
#define IDC_BTN_DEV_REC_SEARCH          1057
#define IDC_EDIT_VERSION_WEB            1058
#define IDC_STATIC_ASSIST               1058
#define IDC_RADIO_SENSOR_IN_1           1059
#define IDC_BTN_HS                      1059
#define IDC_SLIDER_HUE                  1060
#define IDC_EDIT_PORT_RTSP              1060
#define IDC_CHECK_AC                    1060
#define IDC_BTN_VIDEO_MASK              1060
#define IDC_COMBO_STANDARD              1061
#define IDC_EDIT_PORT_WEB               1061
#define IDC_RADIO_SENSOR_IN_2           1061
#define IDC_BTN_BALL_VIDEO_MASK         1061
#define IDC_SLIDER_GAIN                 1061
#define IDC_COMBO_FORMAT                1062
#define IDC_EDIT_PORT_ABC               1062
#define IDC_RADIO_SENSOR_IN_3           1062
#define IDC_EDIT_PORT_UPDATE            1063
#define IDC_CHECK_EMAIL                 1063
#define IDC_COMBO_ENCODER               1064
#define IDC_CHECK_UPNP_OPEN             1064
#define IDC_RADIO_SENSOR_IN_4           1064
#define IDC_CHECK_SENSOR1               1065
#define IDC_EDIT_PORT_FTP               1065
#define IDC_BTN_PORT_WRITE              1066
#define IDC_CHECK_SENSOR2               1066
#define IDC_BTN_WRITE                   1067
#define IDC_EDIT_PPPOE_USER             1067
#define IDC_CHECK_RECORD                1067
#define IDC_BTN_DEF                     1068
#define IDC_BTN_WIFI_WRITE              1068
#define IDC_BTN_LOAD_DEFAULT            1068
#define IDC_EDIT_PPPOE_PWD              1068
#define IDC_CHECK_FTP                   1068
#define IDC_COMBO_INPUT                 1069
#define IDC_CHECK_PPPOE_ENABLE          1069
#define IDC_CHECK_SOUND                 1069
#define IDC_EDIT_NTP_SERVER             1070
#define IDC_EDIT_INTERVAL               1070
#define IDC_CHECK_UPNP_OPEN_RTSP        1070
#define IDC_BTN_PPPOE_WRITE             1071
#define IDC_CHECK_NTP_ENABLE            1071
#define IDC_CHECK_SNAP                  1071
#define IDC_EDIT_TIME                   1072
#define IDC_CHECK_UPNP_OPEN_WEB         1072
#define IDC_EDIT_WIFI_IP                1073
#define IDC_BTN_RESET                   1073
#define IDC_EDIT_DDNS_USER              1073
#define IDC_BNT_WRITE                   1073
#define IDC_EDIT_WIFI_MASK              1074
#define IDC_EDIT_DDNS_PWD               1074
#define IDC_EDIT_WIFI_MAC               1075
#define IDC_EDIT_DDNS_URL               1075
#define IDC_BTN_SEARCH_STOP             1075
#define IDC_EDIT_WIFI_GATEWAY           1076
#define IDC_OSD_CHANNEL                 1076
#define IDC_CHECK_DDNS_OPEN             1076
#define IDC_BTN_SEARCH_START            1076
#define IDC_EDIT_WIFI_SSID              1077
#define IDC_BTN_REBOOT                  1077
#define IDC_LIST_REC_FILE               1077
#define IDC_CHECK_UPNP_OPEN_ABC         1077
#define IDC_COMBO_WIFI_SECTYPE          1078
#define IDC_BTN_DDNS_WRITE              1078
#define IDC_EDIT_VIDEOLOSS_SENSITIVITY  1078
#define IDC_COMBO_PTZ                   1078
#define IDC_COMBO_WIFI_WEPOPT           1079
#define IDC_CHECK_VL_ENABLE             1079
#define IDC_CHECK_UPNP_OPEN_UPDATE      1079
#define IDC_EDIT_DEV_ID                 1079
#define IDC_COMBO_WIFI_WEPINDEX         1080
#define IDC_CHECK_UPNP_OPEN_FTP         1080
#define IDC_EDIT_DEV_NAME               1080
#define IDC_COMBO_WIFI_WEPTYPE          1081
#define IDC_OSD_TIME                    1081
#define IDC_EDIT_DEV_SERVER_ADDR        1081
#define IDC_EDIT_WIFI_WEPPWD            1082
#define IDC_EDIT_DEV_SERVER_PORT        1082
#define IDC_EDIT_WIFI_NAME              1083
#define IDC_EDIT_DEV_AC_ADDR            1083
#define IDC_OSD_BPS                     1084
#define IDC_EDIT_DEV_AC_PORT            1084
#define IDC_EDIT_AO_MAX                 1085
#define IDC_EDIT_AI_MAX                 1086
#define IDC_BTN_SAVE                    1087
#define IDC_BTN_READ                    1088
#define IDC_CHECK_MD_START              1089
#define IDC_EDIT_PWD                    1090
#define IDC_CHECK_MD_STOP               1090
#define IDC_BUTTON_LINK_BUT_NO_VIDEO    1090
#define IDC_CHECK_VL_START              1091
#define IDC_BUTTON_3D                   1091
#define IDC_EDIT_IINTERVAL              1092
#define IDC_CHECK_VL_STOP               1092
#define IDC_BUTTON_DEVCHN               1092
#define IDC_EDIT_FRAMERATE              1093
#define IDC_EDIT_LEFT                   1093
#define IDC_EDIT_BITRATE                1094
#define IDC_EDIT_TOP                    1094
#define IDC_RADIO_CBR                   1095
#define IDC_EDIT_RIGHT                  1095
#define IDC_EDIT_CONTENT                1095
#define IDC_RADIO_VBR                   1096
#define IDC_EDIT_BOTTOM                 1096
#define IDC_EDIT_MULTIPLE               1096
#define IDC_RADIO_PICTURE               1097
#define IDC_STATIC_RECORD_STATUS        1097
#define IDC_RADIO_ZOOM_IN               1097
#define IDC_EDIT_COLOR                  1097
#define IDC_RADIO_FRAME                 1098
#define IDC_BTN_START                   1098
#define IDC_RADIO_ZOOM_OUT              1098
#define IDC_EDIT_LEFT2                  1098
#define IDC_EDIT_BITRATE_MAX            1099
#define IDC_EDIT_DISK_RESERVE           1099
#define IDC_BUTTON_3D_MODE2             1099
#define IDC_EDIT_TOP2                   1099
#define IDC_RADIO_DISK_STOP             1100
#define IDC_BUTTON_MULTI                1100
#define IDC_EDIT_RIGHT2                 1100
#define IDC_RADIO_DISK_DELETE           1101
#define IDC_EDIT_BOTTOM2                1101
#define IDC_EDIT_FILE_MAXTIME           1102
#define IDC_EDIT_CHN_LEFT               1102
#define IDC_EDIT_COLOR2                 1102
#define IDC_RADIO_FILE_STOP             1103
#define IDC_EDIT_CHN_TOP                1103
#define IDC_EDIT_LEFT3                  1103
#define IDC_RADIO_FILE_SWITCH           1104
#define IDC_EDIT_TIME_LEFT              1104
#define IDC_EDIT_TOP3                   1104
#define IDC_LIST_DISK                   1105
#define IDC_EDIT_TIME_TOP               1105
#define IDC_EDIT_RIGHT3                 1105
#define IDC_EDIT_BPS_LEFT               1106
#define IDC_BUTTON_LEFTUP               1106
#define IDC_EDIT_BOTTOM3                1106
#define IDC_EDIT_ALARM_FILE_MAXTIME     1106
#define IDC_BTN_RECORD_READ             1107
#define IDC_EDIT_BPS_TOP                1107
#define IDC_BUTTON_RIGHTUP              1107
#define IDC_EDIT_COLOR3                 1107
#define IDC_BTN_RECORD_SAVE             1108
#define IDC_EDIT_FTP_HOST               1108
#define IDC_BUTTON_LEFTDOWN             1108
#define IDC_EDIT_LEFT4                  1108
#define IDC_EDIT_FTP_USER               1109
#define IDC_BUTTON_RIGHTDOWN            1109
#define IDC_CHECK_VIDEO_MASK            1109
#define IDC_EDIT_FTP_PWD                1110
#define IDC_CHECK_VIDEO_MASK2           1110
#define IDC_RADIO_FTP_PIC               1111
#define IDC_EDIT_INDEX                  1111
#define IDC_CHECK_VIDEO_MASK3           1111
#define IDC_RADIO_FTP_RECORD            1112
#define IDC_EDIT_WIDTH                  1112
#define IDC_EDIT_TOP4                   1112
#define IDC_EDIT_HEIGHT                 1113
#define IDC_EDIT_RIGHT4                 1113
#define IDC_LIST_PRESET                 1114
#define IDC_EDIT_BOTTOM4                1114
#define IDC_BUTTON_SET                  1115
#define IDC_CHECK_VIDEO_MASK4           1115
#define IDC_EDIT_PRESETPOS              1116
#define IDC_BUTTON_SHOW                 1116
#define IDC_BUTTON_WA                   1116
#define IDC_EDIT_COLOR4                 1116
#define IDC_BUTTON_PTZ20                1116
#define IDC_EDIT_PRESETNAME             1117
#define IDC_BUTTON_HIDE                 1117
#define IDC_BUTTON_CLEAR                1117
#define IDC_PTZ_STOP                    1117
#define IDC_BTN_ADD                     1118
#define IDC_BUTTON_DEL                  1118
#define IDC_BUTTON_GET                  1118
#define IDC_BTN_DEL                     1119
#define IDC_BUTTON_CONNECT              1119
#define IDC_BUTTON_SET_COLOR            1119
#define IDC_BUTTON_DISCONNECT           1120
#define IDC_CHECK_MD_ENABLE             1121
#define IDC_NEXT_PAGE                   1121
#define IDC_BTN_INVOKE                  1122
#define IDC_COMBO_CHANNEL               1122
#define IDC_EDIT_SENSITIVITY            1123
#define IDC_LIST1                       1123
#define IDC_LIST_DEV                    1123
#define IDC_EDIT_AREA_LEFT              1124
#define IDC_EDIT1                       1124
#define IDC_EDIT_BRIGHTNESS             1124
#define IDC_EDIT_ID                     1124
#define IDC_EDIT_AREA_TOP               1125
#define IDC_EDIT2                       1125
#define IDC_BUTTON1                     1125
#define IDC_BUTTON_REFRESH              1125
#define IDC_BUTTON_PRESET               1125
#define IDC_BUTTON_PLAYBACK             1125
#define IDC_EDIT_CONTRAST               1125
#define IDC_EDIT_ENCRYPT_STR            1125
#define IDC_EDIT_AREA_WIDTH             1126
#define IDC_EDIT3                       1126
#define IDC_STATIC_MD_AREA              1126
#define IDC_STATIC_MD_GRID              1126
#define IDC_EDIT_DATA1                  1126
#define IDC_EDIT_SATURATION             1126
#define IDC_EDIT_AREA_HEIGHT            1127
#define IDC_EDIT4                       1127
#define IDC_BUTTON_SEQUENCE             1127
#define IDC_EDIT_DATA2                  1127
#define IDC_EDIT_SHARPNESS              1127
#define IDC_EDIT_AREA_LEFT2             1128
#define IDC_BUTTON_AUTO                 1128
#define IDC_EDIT_PACKET                 1128
#define IDC_EDIT_AGC                    1128
#define IDC_EDIT_AREA_TOP2              1129
#define IDC_BUTTON_PATTERN              1129
#define IDC_EDIT_FOCUS_STATUS           1129
#define IDC_EDIT_AREA_WIDTH2            1130
#define IDC_BUTTON_IDLE                 1130
#define IDC_EDIT_SHUTTER_MODE           1130
#define IDC_EDIT_AREA_HEIGHT2           1131
#define IDC_BUTTON_REGION               1131
#define IDC_EDIT_SHUTTER_SPEED          1131
#define IDC_BUTTON_TITLE                1132
#define IDC_EDIT_IRIS                   1132
#define IDC_BUTTON_PRODU                1133
#define IDC_EDIT_GAIN                   1133
#define IDC_BUTTON_MENU                 1134
#define IDC_BUTTON_SYS                  1135
#define IDC_BUTTON_DARM                 1136
#define IDC_EDIT_FTP_PATH               1137
#define IDC_BUTTON_INQ                  1137
#define IDC_BUTTON_VAR                  1138
#define IDC_BUTTON_CMR                  1139
#define IDC_RADIO_ETHERNET              1140
#define IDC_RADIO_WIFI                  1141
#define IDC_BUTTON_CALL                 1141
#define IDC_LIST_WIFI_AP                1142
#define IDC_EDIT_RESULT                 1142
#define IDC_BUTTON_TEST                 1143
#define IDC_LIST_ENC                    1144
#define IDC_COMBO_CMD                   1144
#define IDC_BTN_ENC_ADD                 1145
#define IDC_RADIO_SEQUENCE              1145
#define IDC_BTN_COMSAVE                 1146
#define IDC_BTN_ENC_DEL                 1146
#define IDC_RADIO_AUTO                  1146
#define IDC_BTN_ENC_SAVE                1147
#define IDC_RADIO_PATTERN               1147
#define IDC_COMBO_COM                   1148
#define IDC_CHECK_AUTH_EN               1148
#define IDC_RADIO_IDLE                  1148
#define IDC_COMBO_BITRATE               1149
#define IDC_RADIO_REGION                1149
#define IDC_COMBO_DATABITS              1150
#define IDC_RADIO_TITLE                 1150
#define IDC_COMBO_STOPBITS              1151
#define IDC_LIST_USER                   1151
#define IDC_RADIO_MENU                  1151
#define IDC_RADIO_CMR                   1151
#define IDC_COMBO_CHECKBIT              1152
#define IDC_BTN_USER_ADD                1152
#define IDC_RADIO_SYS                   1152
#define IDC_EDIT_PTZADDRESS             1153
#define IDC_BTN_USER_SET                1153
#define IDC_RADIO_ALL                   1153
#define IDC_RADIO_DARM                  1153
#define IDC_STATIC_USERROL1             1153
#define IDC_EDIT_PTZPROTOCOL            1154
#define IDC_BTN_USER_DEL                1154
#define IDC_RADIO_PTZ                   1154
#define IDC_RADIO_INQ                   1154
#define IDC_STATIC_USERROLE2            1154
#define IDC_COMBO_PTZ_TRACK             1155
#define IDC_RADIO_NORMAL                1155
#define IDC_RADIO_VAR                   1155
#define IDC_STATIC_USERROLE3            1155
#define IDC_COMBO_PTZ_PRESET            1156
#define IDC_RADIO_PRODUCE               1156
#define IDC_COMBO_PTZ_STAYTIME          1157
#define IDC_SLIDER_INPUT                1157
#define IDC_EDIT_HELP                   1157
#define IDC_BUTTON_PLAYBACK_SLOW        1157
#define IDC_BTN_PTZ_ADD                 1158
#define IDC_SLIDER_OUTPUT               1158
#define IDC_BUTTON_PLAYBACK_FAST        1158
#define IDC_BTN_PTZ_DELETE              1159
#define IDC_STATIC_VOL_INPUT            1159
#define IDC_BUTTON_PLAYBACK_PAUSE       1159
#define IDC_LIST_PTZ_TRACK              1160
#define IDC_STATIC_VOL_OUTPUT           1160
#define IDC_BUTTON_PLAYBACK_SEEK        1160
#define IDC_BTN_PTZ_WRITE               1161
#define IDC_COMBO_DDNS_SUPPORT          1161
#define IDC_COMBO_DEV_REC_TYPE          1161
#define IDC_STATIC_DEV_IP               1161
#define IDC_BTN_PTZ_INVOKE              1162
#define IDC_STATIC_CHANNEL              1162
#define IDD_DIALOG_TRACK                1163
#define IDC_STATIC_PORT                 1163
#define IDC_STATIC_USER                 1164
#define IDC_STATIC_PWD                  1165
#define IDC_STATIC_TRANSPORT            1166
#define IDC_STATIC_CONFIG               1167
#define IDC_STATIC_ALARM_CONFIG         1168
#define IDC_STATIC_LANG                 1169
#define IDC_RADIO_CHS                   1170
#define IDC_RADIO_ENG                   1171
#define IDC_STATIC_SERVER               1171
#define IDC_STATIC_AC_PORT              1172
#define IDC_STATIC_SCHE                 1173
#define IDC_STATIC_VOLUME_IN            1174
#define IDC_STATIC_VOLUME_OUT           1175
#define IDC_STATIC_BALL_VM_COLOR        1176
#define IDC_STATIC_BALL_VM_INDEX        1177
#define IDC_STATIC_BALL_VM_WIDTH        1178
#define IDC_STATIC_BALL_VM_HEIGHT       1179
#define IDC_STATIC_I_INTERVAL           1180
#define IDC_STATIC_FPS                  1181
#define IDC_STATIC_BPS                  1182
#define IDC_STATIC_BPS_MAX              1183
#define IDC_STATIC_MD_LINKAGE           1184
#define IDC_STATIC_ALARM_INTERVAL       1185
#define IDC_STATIC_ALARM_INTERVAL_1     1186
#define IDC_STATIC_DURATION             1187
#define IDC_STATIC_DURATION_1           1188
#define IDC_DATE_START                  1189
#define IDC_STATIC_VL_LINKAGE           1189
#define IDC_TIME_START                  1190
#define IDC_STATIC_INTERVAL             1190
#define IDC_DATE_STOP                   1191
#define IDC_STATIC_INTERVAL1            1191
#define IDC_TIME_STOP                   1192
#define IDC_STATIC_LIGHT                1192
#define IDC_STATIC_CONTRAST             1193
#define IDC_STATIC_SATURATION           1194
#define IDC_STATIC_HUE                  1195
#define IDC_STATIC_COM                  1196
#define IDC_STATIC_GAIN                 1196
#define IDC_STATIC_BAUD                 1197
#define IDC_STATIC_FREQUENCY            1197
#define IDC_STATIC_DATA_BIT             1198
#define IDC_STATIC_STOP_BIT             1199
#define IDC_STATIC_CHECK_BIT            1200
#define IDC_STATIC_PTZ_ADDR             1201
#define IDC_STATIC_PROTOCOL             1202
#define IDC_STATIC_STATUS               1203
#define IDC_STATIC_DEV_RECORD           1204
#define IDC_STATIC_STRA                 1205
#define IDC_STATIC_RESERVE              1206
#define IDC_STATIC_NO_SPACE             1207
#define IDC_STATIC_MAX_FILE             1208
#define IDC_STATIC_SECONDS              1209
#define IDC_STATIC_IF_MAX_FILE          1210
#define IDC_STATIC_TIME_START           1211
#define IDC_STATIC_MAX_ALARM_RECORD     1211
#define IDC_STATIC_TIME_STOP            1212
#define IDC_STATIC_SECONDS2             1212
#define IDC_STATIC_TYPE                 1213
#define IDC_STATIC_MAIL_SERVER          1214
#define IDC_STATIC_MAIL_USER            1215
#define IDC_STATIC_MAIL_PASSWORD        1216
#define IDC_STATIC_MAIL                 1217
#define IDC_STATIC_FTP_PWD              1218
#define IDC_STATIC_FTP_PATH             1219
#define IDC_STATIC_THRESHOLD            1220
#define IDC_STATIC_RULE                 1221
#define IDC_STATIC_MD_AREAS             1222
#define IDC_STATIC_ETHERNET             1223
#define IDC_STATIC_IP                   1224
#define IDC_STATIC_MAC                  1225
#define IDC_STATIC_MASK                 1226
#define IDC_STATIC_GW                   1227
#define IDC_STATIC_DMOMAIN              1228
#define IDC_STATIC_WIFI                 1229
#define IDC_STATIC_WIFI_NAME            1230
#define IDC_STATIC_WIFI_IP              1231
#define IDC_STATIC_WIFI_MASK            1232
#define IDC_STATIC_WIFI_MAC             1233
#define IDC_STATIC_WIFI_GW              1234
#define IDC_STATIC_WIFI_DOMAIN          1235
#define IDC_STATIC_SECU_TYPE            1236
#define IDC_STATIC_SECU_CHECK           1237
#define IDC_STATIC_SECU_KEY             1238
#define IDC_STATIC_SECU_KEY_LEN         1239
#define IDC_STATIC_SECU_KEY_PRIVATE     1240
#define IDC_STATIC_OSD_NAME             1241
#define IDC_STATIC_PRESET_ID            1242
#define IDC_STATIC_PRESET_NAME          1243
#define IDC_STATIC_GUARD                1244
#define IDC_STATIC_GUARD_PRESET         1245
#define IDC_STATIC_HOMING_INTERVAL      1246
#define IDC_STATIC_CMD                  1247
#define IDC_STATIC_SYSNAME              1248
#define IDC_STATIC_SYSID                1249
#define IDC_STATIC_SYSVER               1250
#define IDC_STATIC_SYSWEBVER            1251
#define IDC_STATIC_SYSSERVERVER         1252
#define IDC_STATIC_SYSCHANNELNUM        1253
#define IDC_STATIC_SYSVIDEOIN           1254
#define IDC_STATIC_SYSCODEC             1255
#define IDC_STATIC_SYSVIDEOSIZE         1256
#define IDC_STATIC_SYSSTAND             1257
#define IDC_STATIC_TZ                   1258
#define IDC_STATIC_TIME                 1259
#define IDC_STATIC_NTP                  1260
#define IDC_STATIC_TRACKID              1261
#define IDC_STATIC_TRACKPRESET          1262
#define IDC_STATIC_TRACKINTERVAL        1263
#define IDC_STATIC_USERNAME             1264
#define IDC_STATIC_USERPWD              1265
#define IDC_STATIC_USERNAME1            1266
#define IDC_STATIC_USERPWD1             1267
#define IDC_STATIC_COLOR                1268
#define IDC_STATIC_COLOR1               1269
#define IDC_STATIC_COLOR2               1270
#define IDC_STATIC_COLOR3               1271
#define IDC_STATIC_LEFT                 1272
#define IDC_STATIC_LEFT1                1273
#define IDC_STATIC_LEFT2                1274
#define IDC_STATIC_LEFT3                1275
#define IDC_STATIC_TOP                  1276
#define IDC_STATIC_TOP1                 1277
#define IDC_STATIC_TOP2                 1278
#define IDC_STATIC_TOP3                 1279
#define IDC_STATIC_RIGHT                1280
#define IDC_STATIC_RIGHT1               1281
#define IDC_STATIC_RIGHT2               1282
#define IDC_STATIC_RIGHT3               1283
#define IDC_STATIC_BOTTOM               1284
#define IDC_STATIC_BOTTOM1              1285
#define IDC_STATIC_BOTTOM2              1286
#define IDC_STATIC_BOTTOM3              1287
#define IDC_STATIC_THRE                 1288
#define IDC_BUTTON_WA_IMAGE             1289
#define IDC_BUTTON_ENCRYPT_STR          1290
#define IDC_BUTTON_SAVE                 1290
#define IDC_BUTTON_SET_DEFAULT          1291
#define IDC_BUTTON_SET_SHUTTER_MODE     1292
#define IDC_BUTTON_SET_SHUTTER_SPEED    1293
#define IDC_BUTTON_VIDEODECODER         1293
#define IDC_BUTTON_SET_NORTH            1294
#define IDC_BUTTON_AUDIODECODER         1294
#define IDC_BUTTON_SHOW_ANGLE           1295
#define IDC_RADIO_FREQUENCY_60          1296
#define IDC_RADIO_FREQUENCY_50          1297
#define IDC_RADIO1                      1298
#define IDC_CHECK_AUDIO_IN              1456
#define IDC_STATIC_AR_CODEC             1457
#define IDC_RADIO_AR_G711U              1458
#define IDC_RADIO_AR_G711A              1458
#define IDC_RADIO_AR_AMRNB              1459
#define IDC_RADIO_AR_G711MU             1459

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        169
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1299
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
